import { contextBridge, ipcRenderer } from 'electron'

contextBridge.exposeInMainWorld('electronAPI', {
  // Window controls
  minimizeWindow: () => ipcRenderer.invoke('window:minimize'),
  maximizeWindow: () => ipcRenderer.invoke('window:maximize'),
  closeWindow: () => ipcRenderer.invoke('window:close'),
  isMaximized: () => ipcRenderer.invoke('window:isMaximized'),

  // URL detection
  detectUrl: (url: string) => ipcRenderer.invoke('url:detect', url),
  cancelDetection: () => ipcRenderer.invoke('url:cancelDetect'),

  // Formats
  getFormats: (url: string) => ipcRenderer.invoke('formats:get', url),

  // Subtitles
  getSubtitles: (url: string) => ipcRenderer.invoke('subtitles:get', url),

  // Download
  startDownload: (options: {
    url: string
    format: string
    audioOnly?: boolean
    outputPath?: string
  }) => ipcRenderer.invoke('download:start', options),

  cancelDownload: () => ipcRenderer.invoke('download:cancel'),

  onDownloadProgress: (callback: (progress: {
    percent: number
    speed?: string
    eta?: string
    downloaded?: string
    total?: string
    currentFile?: string
    currentIndex?: number
    totalFiles?: number
    status: string
  }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, progress: Parameters<typeof callback>[0]) => callback(progress)
    ipcRenderer.on('download:progress', subscription)
    return () => ipcRenderer.removeListener('download:progress', subscription)
  },

  onDownloadComplete: (callback: (result: {
    success: boolean
    filePath?: string
    error?: string
  }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, result: Parameters<typeof callback>[0]) => callback(result)
    ipcRenderer.on('download:complete', subscription)
    return () => ipcRenderer.removeListener('download:complete', subscription)
  },

  onDownloadError: (callback: (error: string) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, error: string) => callback(error)
    ipcRenderer.on('download:error', subscription)
    return () => ipcRenderer.removeListener('download:error', subscription)
  },

  onVideoComplete: (callback: (videoInfo: {
    index: number
    totalFiles: number
    title: string
    filePath: string
    alreadyDownloaded?: boolean
  }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, videoInfo: Parameters<typeof callback>[0]) => callback(videoInfo)
    ipcRenderer.on('download:videoComplete', subscription)
    return () => ipcRenderer.removeListener('download:videoComplete', subscription)
  },

  // Settings
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings: Record<string, unknown>) => ipcRenderer.invoke('settings:save', settings),

  // History
  getHistory: () => ipcRenderer.invoke('history:get'),
  addToHistory: (item: {
    id: string
    title: string
    url: string
    thumbnail?: string
    downloadDate: string
    filePath: string
    fileSize?: number
    duration?: number
    status: 'completed' | 'failed' | 'cancelled'
    type: 'video' | 'playlist' | 'channel'
    videoCount?: number
  }) => ipcRenderer.invoke('history:add', item),
  removeFromHistory: (id: string) => ipcRenderer.invoke('history:remove', id),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  onHistoryAdded: (callback: (item: {
    id: string
    title: string
    url: string
    thumbnail?: string
    downloadDate: string
    filePath: string
    status: string
    type: string
  }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, item: Parameters<typeof callback>[0]) => callback(item)
    ipcRenderer.on('history:added', subscription)
    return () => ipcRenderer.removeListener('history:added', subscription)
  },

  // File operations
  openFile: (filePath: string) => ipcRenderer.invoke('file:open', filePath),
  openFolder: (filePath: string) => ipcRenderer.invoke('file:showInFolder', filePath),
  selectFolder: () => ipcRenderer.invoke('folder:select'),

  // Queue operations
  getQueue: () => ipcRenderer.invoke('queue:get'),
  addToQueue: (item: {
    url: string
    title: string
    thumbnail?: string
    format: string
    qualityLabel?: string
    audioOnly: boolean
    source: 'app' | 'extension'
    sourceType?: 'single' | 'playlist' | 'channel'
    contentType?: 'video' | 'audio' | 'subtitle' | 'video+sub'
    subtitleOptions?: {
      enabled: boolean
      languages: string[]
      includeAutoGenerated: boolean
      format: 'srt' | 'vtt' | 'ass'
      embedInVideo: boolean
    }
  }) => ipcRenderer.invoke('queue:add', item),
  removeFromQueue: (id: string) => ipcRenderer.invoke('queue:remove', id),
  cancelQueueItem: (id: string) => ipcRenderer.invoke('queue:cancel', id),
  pauseQueueItem: (id: string) => ipcRenderer.invoke('queue:pauseItem', id),
  resumeQueueItem: (id: string) => ipcRenderer.invoke('queue:resumeItem', id),
  pauseQueue: () => ipcRenderer.invoke('queue:pause'),
  resumeQueue: () => ipcRenderer.invoke('queue:resume'),
  clearQueue: () => ipcRenderer.invoke('queue:clear'),
  retryQueueItem: (id: string) => ipcRenderer.invoke('queue:retry', id),
  retryAllFailed: () => ipcRenderer.invoke('queue:retryAllFailed'),
  onQueueUpdate: (callback: (status: {
    items: Array<{
      id: string
      url: string
      title: string
      thumbnail?: string
      format: string
      audioOnly: boolean
      status: 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled' | 'paused'
      progress?: {
        percent: number
        speed?: string
        eta?: string
        status: string
      }
      addedAt: number
      source: 'app' | 'extension'
      error?: string
    }>
    isProcessing: boolean
    isPaused: boolean
    currentItemId: string | null
  }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, status: Parameters<typeof callback>[0]) => callback(status)
    ipcRenderer.on('queue:update', subscription)
    return () => ipcRenderer.removeListener('queue:update', subscription)
  },

  // Logger operations
  getErrorLogs: () => ipcRenderer.invoke('logger:getErrors'),
  openLogFile: () => ipcRenderer.invoke('logger:openLogFile'),

  // Binary management
  checkBinary: () => ipcRenderer.invoke('binary:check'),
  downloadBinary: () => ipcRenderer.invoke('binary:download'),
  getBinaryStatus: () => ipcRenderer.invoke('binary:status'),
  onBinaryDownloadStart: (callback: (data: { name: string }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, data: Parameters<typeof callback>[0]) => callback(data)
    ipcRenderer.on('binary:download-start', subscription)
    return () => ipcRenderer.removeListener('binary:download-start', subscription)
  },
  onBinaryDownloadProgress: (callback: (data: { percent: number; downloaded: number; total: number }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, data: Parameters<typeof callback>[0]) => callback(data)
    ipcRenderer.on('binary:download-progress', subscription)
    return () => ipcRenderer.removeListener('binary:download-progress', subscription)
  },
  onBinaryDownloadComplete: (callback: (data: { path: string }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, data: Parameters<typeof callback>[0]) => callback(data)
    ipcRenderer.on('binary:download-complete', subscription)
    return () => ipcRenderer.removeListener('binary:download-complete', subscription)
  },
  onBinaryDownloadError: (callback: (data: { error: string }) => void) => {
    const subscription = (_event: Electron.IpcRendererEvent, data: Parameters<typeof callback>[0]) => callback(data)
    ipcRenderer.on('binary:download-error', subscription)
    return () => ipcRenderer.removeListener('binary:download-error', subscription)
  },
})
