#!/usr/bin/env node

/**
 * Update Version Script
 * 
 * This script reads the version from version.json and updates it across all project files:
 * - package.json
 * - extension/manifest.json
 * - src/version.ts (auto-generated)
 * 
 * Usage: node scripts/update-version.js
 */

const fs = require('fs');
const path = require('path');

// Read version from version.json
const versionPath = path.join(__dirname, '..', 'version.json');
const versionData = JSON.parse(fs.readFileSync(versionPath, 'utf8'));
const { version } = versionData;

console.log(`📦 Updating project to version ${version}...`);

// Update package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
packageJson.version = version;
fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2) + '\n');
console.log(`✅ Updated package.json`);

// Update extension/manifest.json
const manifestPath = path.join(__dirname, '..', 'extension', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
manifest.version = version;
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
console.log(`✅ Updated extension/manifest.json`);

// Generate src/version.ts
const versionTsPath = path.join(__dirname, '..', 'src', 'version.ts');
const versionTsContent = `/**
 * Application Version
 * 
 * This file is auto-generated by scripts/update-version.js
 * DO NOT EDIT MANUALLY - Edit version.json instead
 */

export const APP_VERSION = "${version}";
`;
fs.writeFileSync(versionTsPath, versionTsContent);
console.log(`✅ Generated src/version.ts`);

console.log(`\n🎉 Version ${version} updated successfully across all files!`);
