export interface VideoFormat {
  formatId: string
  ext: string
  resolution: string
  quality: string
  filesize?: number
  fps?: number
  vcodec?: string
  acodec?: string
  isAudioOnly: boolean
}

export interface ContentInfo {
  type: 'video' | 'playlist' | 'channel'
  id: string
  title: string
  thumbnail?: string
  duration?: number
  uploaderName?: string
  uploaderUrl?: string
  description?: string
  videoCount?: number
  entries?: PlaylistEntry[]
}

export interface PlaylistEntry {
  id: string
  title: string
  duration?: number
  thumbnail?: string
  index: number
  selected?: boolean
}

export type PlaylistSelectionMode = 'all' | 'selected' | 'range'

export interface PlaylistDownloadOptions {
  mode: PlaylistSelectionMode
  selectedIndices?: number[]  // For 'selected' mode
  rangeStart?: number         // For 'range' mode
  rangeEnd?: number
}

export interface SubtitleInfo {
  lang: string          // "en", "es", etc.
  langName: string      // "English", "Spanish"
  isAutoGenerated: boolean
  ext: string           // "vtt", "srt"
}

export interface SubtitleOptions {
  enabled: boolean
  languages: string[]
  includeAutoGenerated: boolean
  format: 'srt' | 'vtt' | 'ass'
  embedInVideo: boolean
}

export interface DownloadProgress {
  percent: number
  speed?: string
  eta?: string
  downloaded?: string
  total?: string
  currentFile?: string
  currentIndex?: number
  totalFiles?: number
  status: 'downloading' | 'merging' | 'processing' | 'complete' | 'error' | 'waiting'
}

export interface DownloadOptions {
  url: string
  format: string
  quality?: string
  audioOnly?: boolean
  outputPath?: string
}

export interface HistoryItem {
  id: string
  title: string
  url: string
  thumbnail?: string
  downloadDate: string
  filePath: string
  fileSize?: number
  duration?: number
  status: 'completed' | 'failed' | 'cancelled'
  type: 'video' | 'playlist' | 'channel'
  videoCount?: number
}

export interface QueueItem {
  id: string
  url: string
  title: string
  thumbnail?: string
  format: string
  qualityLabel?: string
  audioOnly: boolean
  status: 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled' | 'paused'
  progress?: DownloadProgress
  addedAt: number
  source: 'app' | 'extension'
  sourceType?: 'single' | 'playlist' | 'channel'
  contentType?: 'video' | 'audio' | 'subtitle' | 'video+sub'
  subtitleOptions?: SubtitleOptions
  subtitleDisplayNames?: string  // Human-readable names like "English, Spanish"
  error?: string
}

export interface LogEntry {
  timestamp: string
  level: 'info' | 'warn' | 'error'
  message: string
  details?: string
}

export interface QueueStatus {
  items: QueueItem[]
  isProcessing: boolean
  isPaused: boolean
  currentItemId: string | null
}

// Update-related types
export interface UpdateInfo {
  version: string
  currentVersion: string
  releaseDate: string
  releaseNotes: string
  downloadUrl: string
  mandatory: boolean
}

export interface UpdateProgress {
  percent: number
  transferred: number
  total: number
  bytesPerSecond: number
}

export interface UpdateStatus {
  checking: boolean
  available: boolean
  downloading: boolean
  downloaded: boolean
  error: string | null
  info: UpdateInfo | null
  progress: UpdateProgress | null
}

export interface ChangelogSection {
  added: string[]
  changed: string[]
  fixed: string[]
  removed: string[]
}

export interface ChangelogData {
  version: string
  date: string
  sections: ChangelogSection
}

export interface UpdateState {
  lastVersionLaunched: string
  lastUpdateCheck: string | null
  updateSkippedVersion: string | null
  changelogSeenForVersion: string
}

export interface AppSettings {
  downloadPath: string
  defaultQuality: string
  defaultFormat: 'mp4' | 'mp3' | 'm4a' | 'webm'
  organizeByType: boolean
  autoStartDownload: boolean
  autoBestQuality: boolean
  maxConcurrentDownloads: number
  delayBetweenDownloads: number
  theme: 'light' | 'dark' | 'system'
  fontSize: 'small' | 'medium' | 'large' | 'x-large'
}

export interface ElectronAPI {
  // Window controls
  minimizeWindow: () => Promise<void>
  maximizeWindow: () => Promise<void>
  closeWindow: () => Promise<void>
  isMaximized: () => Promise<boolean>

  detectUrl: (url: string) => Promise<ContentInfo>
  cancelDetection: () => Promise<void>
  getFormats: (url: string) => Promise<VideoFormat[]>
  getSubtitles: (url: string) => Promise<SubtitleInfo[]>
  startDownload: (options: DownloadOptions) => Promise<void>
  cancelDownload: () => Promise<void>
  onDownloadProgress: (callback: (progress: DownloadProgress) => void) => () => void
  onDownloadComplete: (callback: (result: { success: boolean; filePath?: string; error?: string }) => void) => () => void
  onDownloadError: (callback: (error: string) => void) => () => void
  onVideoComplete: (callback: (videoInfo: {
    index: number
    totalFiles: number
    title: string
    filePath: string
    alreadyDownloaded?: boolean
  }) => void) => () => void
  getSettings: () => Promise<AppSettings>
  saveSettings: (settings: Partial<AppSettings>) => Promise<void>
  getHistory: () => Promise<HistoryItem[]>
  addToHistory: (item: HistoryItem) => Promise<void>
  clearHistory: () => Promise<void>
  removeFromHistory: (id: string) => Promise<void>
  onHistoryAdded: (callback: (item: HistoryItem) => void) => () => void
  openFile: (filePath: string) => Promise<void>
  openFolder: (filePath: string) => Promise<void>
  selectFolder: () => Promise<string | null>

  // Queue operations
  getQueue: () => Promise<QueueStatus>
  addToQueue: (item: {
    url: string
    title: string
    thumbnail?: string
    format: string
    qualityLabel?: string
    audioOnly: boolean
    source: 'app' | 'extension'
    sourceType?: 'single' | 'playlist' | 'channel'
    contentType?: 'video' | 'audio' | 'subtitle' | 'video+sub'
    subtitleOptions?: SubtitleOptions
    subtitleDisplayNames?: string
  }) => Promise<{ id: string; position: number }>
  removeFromQueue: (id: string) => Promise<void>
  cancelQueueItem: (id: string) => Promise<void>
  pauseQueueItem: (id: string) => Promise<boolean>
  resumeQueueItem: (id: string) => Promise<boolean>
  pauseQueue: () => Promise<void>
  resumeQueue: () => Promise<void>
  clearQueue: () => Promise<void>
  retryQueueItem: (id: string) => Promise<boolean>
  retryAllFailed: () => Promise<number>
  onQueueUpdate: (callback: (status: QueueStatus) => void) => () => void

  // Logger operations
  getErrorLogs: () => Promise<LogEntry[]>
  openLogFile: () => Promise<void>

  // Binary management
  checkBinary: () => Promise<boolean>
  downloadBinary: () => Promise<boolean>
  getBinaryStatus: () => Promise<{
    ytdlp: { installed: boolean; version: string | null; path: string | null }
    ffmpeg: { available: boolean; version: string | null; path: string | null }
    ffprobe: { available: boolean; path: string | null }
  }>
  onBinaryDownloadStart: (callback: (data: { name: string }) => void) => () => void
  onBinaryDownloadProgress: (callback: (data: { percent: number; downloaded: number; total: number }) => void) => () => void
  onBinaryDownloadComplete: (callback: (data: { path: string }) => void) => () => void
  onBinaryDownloadError: (callback: (data: { error: string }) => void) => () => void

  // Update operations
  checkForUpdates: () => Promise<UpdateInfo | null>
  downloadUpdate: () => Promise<string | null>
  installUpdate: () => Promise<void>
  getUpdateStatus: () => Promise<UpdateStatus>
  cancelUpdate: () => Promise<void>
  getChangelog: (body: string, version: string) => Promise<ChangelogData>
  markChangelogSeen: () => Promise<void>
  getUpdateState: () => Promise<UpdateState>
  skipUpdateVersion: (version: string) => Promise<void>
  resetUpdate: () => Promise<void>
  fetchChangelogFromMain: (version: string) => Promise<ChangelogData>

  // Update event listeners
  onUpdateChecking: (callback: () => void) => () => void
  onUpdateAvailable: (callback: (info: UpdateInfo) => void) => () => void
  onUpdateNotAvailable: (callback: () => void) => () => void
  onUpdateProgress: (callback: (progress: UpdateProgress) => void) => () => void
  onUpdateDownloaded: (callback: (filePath: string) => void) => () => void
  onUpdateError: (callback: (error: string) => void) => () => void
  onUpdateCancelled: (callback: () => void) => () => void
  onShowChangelog: (callback: (version: string) => void) => () => void
  onLinuxDeb: (callback: (filePath: string) => void) => () => void
  onLinuxAppImage: (callback: (filePath: string) => void) => () => void
}

declare global {
  interface Window {
    electronAPI: ElectronAPI
  }
}
