export interface VideoFormat {
  formatId: string
  ext: string
  resolution: string
  quality: string
  filesize?: number
  fps?: number
  vcodec?: string
  acodec?: string
  isAudioOnly: boolean
}

export interface ContentInfo {
  type: 'video' | 'playlist' | 'channel'
  id: string
  title: string
  thumbnail?: string
  duration?: number
  uploaderName?: string
  uploaderUrl?: string
  description?: string
  videoCount?: number
  entries?: PlaylistEntry[]
}

export interface PlaylistEntry {
  id: string
  title: string
  duration?: number
  thumbnail?: string
  index: number
  selected?: boolean
}

export type PlaylistSelectionMode = 'all' | 'selected' | 'range'

export interface PlaylistDownloadOptions {
  mode: PlaylistSelectionMode
  selectedIndices?: number[]  // For 'selected' mode
  rangeStart?: number         // For 'range' mode
  rangeEnd?: number
}

export interface SubtitleInfo {
  lang: string          // "en", "es", etc.
  langName: string      // "English", "Spanish"
  isAutoGenerated: boolean
  ext: string           // "vtt", "srt"
}

export interface SubtitleOptions {
  enabled: boolean
  languages: string[]
  includeAutoGenerated: boolean
  format: 'srt' | 'vtt' | 'ass'
  embedInVideo: boolean
}

export interface DownloadProgress {
  percent: number
  speed?: string
  eta?: string
  downloaded?: string
  total?: string
  currentFile?: string
  currentIndex?: number
  totalFiles?: number
  status: 'downloading' | 'merging' | 'processing' | 'complete' | 'error' | 'waiting'
}

export interface DownloadOptions {
  url: string
  format: string
  quality?: string
  audioOnly?: boolean
  outputPath?: string
}

export interface HistoryItem {
  id: string
  title: string
  url: string
  thumbnail?: string
  downloadDate: string
  filePath: string
  fileSize?: number
  duration?: number
  status: 'completed' | 'failed' | 'cancelled'
  type: 'video' | 'playlist' | 'channel'
  videoCount?: number
}

export interface QueueItem {
  id: string
  url: string
  title: string
  thumbnail?: string
  format: string
  audioOnly: boolean
  status: 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled' | 'paused'
  progress?: DownloadProgress
  addedAt: number
  source: 'app' | 'extension'
  error?: string
}

export interface LogEntry {
  timestamp: string
  level: 'info' | 'warn' | 'error'
  message: string
  details?: string
}

export interface QueueStatus {
  items: QueueItem[]
  isProcessing: boolean
  isPaused: boolean
  currentItemId: string | null
}

export interface AppSettings {
  downloadPath: string
  defaultQuality: string
  defaultFormat: 'mp4' | 'mp3' | 'm4a' | 'webm'
  organizeByType: boolean
  autoStartDownload: boolean
  autoBestQuality: boolean
  maxConcurrentDownloads: number
  delayBetweenDownloads: number
  theme: 'light' | 'dark' | 'system'
  fontSize: 'small' | 'medium' | 'large' | 'x-large'
}

export interface ElectronAPI {
  // Window controls
  minimizeWindow: () => Promise<void>
  maximizeWindow: () => Promise<void>
  closeWindow: () => Promise<void>
  isMaximized: () => Promise<boolean>

  detectUrl: (url: string) => Promise<ContentInfo>
  cancelDetection: () => Promise<void>
  getFormats: (url: string) => Promise<VideoFormat[]>
  getSubtitles: (url: string) => Promise<SubtitleInfo[]>
  startDownload: (options: DownloadOptions) => Promise<void>
  cancelDownload: () => Promise<void>
  onDownloadProgress: (callback: (progress: DownloadProgress) => void) => () => void
  onDownloadComplete: (callback: (result: { success: boolean; filePath?: string; error?: string }) => void) => () => void
  onDownloadError: (callback: (error: string) => void) => () => void
  onVideoComplete: (callback: (videoInfo: {
    index: number
    totalFiles: number
    title: string
    filePath: string
    alreadyDownloaded?: boolean
  }) => void) => () => void
  getSettings: () => Promise<AppSettings>
  saveSettings: (settings: Partial<AppSettings>) => Promise<void>
  getHistory: () => Promise<HistoryItem[]>
  addToHistory: (item: HistoryItem) => Promise<void>
  clearHistory: () => Promise<void>
  removeFromHistory: (id: string) => Promise<void>
  onHistoryAdded: (callback: (item: HistoryItem) => void) => () => void
  openFile: (filePath: string) => Promise<void>
  openFolder: (filePath: string) => Promise<void>
  selectFolder: () => Promise<string | null>

  // Queue operations
  getQueue: () => Promise<QueueStatus>
  addToQueue: (item: { url: string; title: string; thumbnail?: string; format: string; audioOnly: boolean; source: 'app' | 'extension' }) => Promise<{ id: string; position: number }>
  removeFromQueue: (id: string) => Promise<void>
  cancelQueueItem: (id: string) => Promise<void>
  pauseQueue: () => Promise<void>
  resumeQueue: () => Promise<void>
  clearQueue: () => Promise<void>
  onQueueUpdate: (callback: (status: QueueStatus) => void) => () => void

  // Logger operations
  getErrorLogs: () => Promise<LogEntry[]>
  openLogFile: () => Promise<void>

  // Binary management
  checkBinary: () => Promise<boolean>
  downloadBinary: () => Promise<boolean>
  onBinaryDownloadStart: (callback: (data: { name: string }) => void) => () => void
  onBinaryDownloadProgress: (callback: (data: { percent: number; downloaded: number; total: number }) => void) => () => void
  onBinaryDownloadComplete: (callback: (data: { path: string }) => void) => () => void
  onBinaryDownloadError: (callback: (data: { error: string }) => void) => () => void
}

declare global {
  interface Window {
    electronAPI: ElectronAPI
  }
}
