export interface VideoFormat {
  formatId: string
  ext: string
  resolution: string
  quality: string
  filesize?: number
  fps?: number
  vcodec?: string
  acodec?: string
  isAudioOnly: boolean
}

export interface SearchResult {
  id: string
  title: string
  thumbnail?: string
  duration?: number
  uploader?: string
  viewCount?: number
  url: string
  type: 'video' | 'playlist' | 'channel'
}

export interface ContentInfo {
  type: 'video' | 'playlist' | 'channel'
  id: string
  url: string  // Original URL for multi-platform support
  title: string
  thumbnail?: string
  duration?: number
  uploaderName?: string
  uploaderUrl?: string
  description?: string
  videoCount?: number
  entries?: PlaylistEntry[]
}

export interface PlaylistEntry {
  id: string
  url: string  // Full URL for multi-platform support
  title: string
  duration?: number
  thumbnail?: string
  index: number
  selected?: boolean
}

export type PlaylistSelectionMode = 'all' | 'selected' | 'range'

export interface PlaylistDownloadOptions {
  mode: PlaylistSelectionMode
  selectedIndices?: number[]  // For 'selected' mode
  rangeStart?: number         // For 'range' mode
  rangeEnd?: number
}

export interface SubtitleInfo {
  lang: string          // "en", "es", etc.
  langName: string      // "English", "Spanish"
  isAutoGenerated: boolean
  ext: string           // "vtt", "srt"
}

export interface SubtitleOptions {
  enabled: boolean
  languages: string[]
  includeAutoGenerated: boolean
  format: 'srt' | 'vtt' | 'ass'
  embedInVideo: boolean
}

export interface DownloadProgress {
  percent: number
  speed?: string
  eta?: string
  downloaded?: string
  total?: string
  currentFile?: string
  currentIndex?: number
  totalFiles?: number
  status: 'downloading' | 'merging' | 'processing' | 'complete' | 'error' | 'waiting'
}

export interface DownloadOptions {
  url: string
  format: string
  quality?: string
  audioOnly?: boolean
  outputPath?: string
}

export interface HistoryItem {
  id: string
  title: string
  url: string
  thumbnail?: string
  downloadDate: string
  filePath: string
  fileSize?: number
  duration?: number
  status: 'completed' | 'failed' | 'cancelled'
  type: 'video' | 'playlist' | 'channel'
  videoCount?: number
}

export interface QueueItem {
  id: string
  url: string
  title: string
  thumbnail?: string
  channel?: string // Channel/uploader name for analytics
  platform?: string // 'youtube' | 'tiktok' | 'twitch' | 'twitter' | etc.
  format: string
  qualityLabel?: string
  audioOnly: boolean
  status: 'pending' | 'downloading' | 'completed' | 'failed' | 'cancelled' | 'paused' | 'retrying'
  progress?: DownloadProgress
  addedAt: number
  source: 'app' | 'extension' | 'cloud'
  sourceType?: 'single' | 'playlist' | 'channel'
  contentType?: 'video' | 'audio' | 'subtitle' | 'video+sub'
  subtitleOptions?: SubtitleOptions
  subtitleDisplayNames?: string  // Human-readable names like "English, Spanish"
  batchGroupId?: string
  error?: string
  retryCount?: number
  nextRetryAt?: number
  autoRetryEnabled?: boolean
  priority?: number // 0 = normal (default), higher = more urgent. 1 = "Download Next"
}

export interface LogEntry {
  timestamp: string
  level: 'info' | 'warn' | 'error'
  message: string
  details?: string
}

export interface QueueStatus {
  items: QueueItem[]
  isProcessing: boolean
  isPaused: boolean
  currentItemId: string | null
  batchStatus: BatchStatus | null
  countdownInfo: CountdownInfo | null
}

export interface BatchStatus {
  active: boolean
  groupId: string | null
  batchNumber: number
  totalBatches: number
  itemsInCurrentBatch: number
  batchSize: number
  totalItems: number
  completedItems: number
  isPaused: boolean
  pauseRemaining: number
  pauseDuration: number
}

export interface CountdownInfo {
  type: 'batch-pause' | 'download-delay' | 'retry-delay' | 'none'
  remaining: number
  total: number
  label: string
}

export interface PotTokenStatus {
  running: boolean
  port: number
  lastTokenTime: string | null
  tokenCount: number
  error: string | null
  uptime: number
}

// Update-related types
export interface UpdateInfo {
  version: string
  currentVersion: string
  releaseDate: string
  releaseNotes: string
  downloadUrl: string
  mandatory: boolean
}

export interface UpdateProgress {
  percent: number
  transferred: number
  total: number
  bytesPerSecond: number
}

export interface UpdateStatus {
  checking: boolean
  available: boolean
  downloading: boolean
  downloaded: boolean
  error: string | null
  info: UpdateInfo | null
  progress: UpdateProgress | null
}

export interface ChangelogSection {
  added: string[]
  changed: string[]
  fixed: string[]
  removed: string[]
}

export interface ChangelogData {
  version: string
  date: string
  sections: ChangelogSection
}

export interface UpdateState {
  lastVersionLaunched: string | null
  lastUpdateCheck: string | null
  updateSkippedVersion: string | null
  changelogSeenForVersion: string
}

export interface ThemeColors {
  name: string
  displayName: string
  colors: {
    accent: string
    accentHover: string
    accentLight: string
    success: string
    warning: string
    error: string
  }
}

export type SoundNotificationMode = 'every' | 'each-item' | 'batch-complete'

export interface CloudSyncConfig {
  apiUrl: string
  apiKey: string
  userId: string
  pollInterval: number
}

export interface CloudSyncStatus {
  enabled: boolean
  polling: boolean
  lastPoll: string | null
  error?: string
  itemsFound?: number
}

export interface AppSettings {
  downloadPath: string
  defaultQuality: string
  defaultFormat: 'mp4' | 'mp3' | 'm4a' | 'webm'
  organizeByType: boolean
  autoStartDownload: boolean
  autoBestQuality: boolean
  maxConcurrentDownloads: number
  delayBetweenDownloads: number
  theme: 'light' | 'dark' | 'system'
  selectedTheme: string  // 'purple', 'ocean', 'forest', 'sunset', 'midnight', 'rose', 'cyan', 'emerald', 'custom'
  customAccentColor: string  // Hex color for custom theme
  fontSize: 'small' | 'medium' | 'large' | 'x-large'
  batchSize: number
  batchPauseShort: number
  batchPauseLong: number
  batchDownloadEnabled: boolean
  potTokenEnabled: boolean
  potTokenPort: number
  potTokenTTL: number
  speedLimit: string  // e.g., '1M', '5M', '10M', or empty for unlimited
  soundEnabled: boolean
  soundVolume: number  // 0-100
  soundNotificationMode: SoundNotificationMode  // 'every', 'each-item', 'batch-complete'
  autoRetryEnabled: boolean
  maxRetries: number
  closeToTray: boolean  // Minimize to system tray instead of closing
  shutdownAfterComplete: boolean  // Auto-shutdown when queue done
  writeThumbnail: boolean  // Download video thumbnail
  writeDescription: boolean  // Save video description as text file
  smartFilename: boolean  // Clean up filenames (remove emojis, restrict to ASCII)
  downloadAllSubtitles: boolean  // Download all available subtitle languages
  preferAV1: boolean  // Prefer AV1 codec for better compression
  preferHDR: boolean  // Preserve HDR metadata when available
  downloadAllComments: boolean  // Download video comments as JSON
  cloudSyncEnabled: boolean  // Enable Grab cloud sync
  cloudApiUrl: string  // Grab cloud API URL
  cloudApiKey: string  // Desktop API key
  cloudUserId: string  // Cloud user ID
  cloudPollInterval: number  // Poll interval in ms
}

export interface ElectronAPI {
  // Window controls
  minimizeWindow: () => Promise<void>
  maximizeWindow: () => Promise<void>
  closeWindow: () => Promise<void>
  minimizeToTray: () => Promise<void>
  forceQuit: () => Promise<void>
  isMaximized: () => Promise<boolean>

  // Mini mode
  toggleMiniMode: () => Promise<boolean>
  setAlwaysOnTop: (enabled: boolean) => Promise<void>
  getMiniModeState: () => Promise<boolean>
  onMiniModeChanged: (callback: (isMini: boolean) => void) => () => void

  detectUrl: (url: string) => Promise<ContentInfo>
  cancelDetection: () => Promise<void>
  getFormats: (url: string) => Promise<VideoFormat[]>
  getSubtitles: (url: string) => Promise<SubtitleInfo[]>
  startDownload: (options: DownloadOptions) => Promise<void>
  cancelDownload: () => Promise<void>
  onDownloadProgress: (callback: (progress: DownloadProgress) => void) => () => void
  onDownloadComplete: (callback: (result: { success: boolean; filePath?: string; error?: string }) => void) => () => void
  onDownloadError: (callback: (error: string) => void) => () => void
  onVideoComplete: (callback: (videoInfo: {
    index: number
    totalFiles: number
    title: string
    filePath: string
    alreadyDownloaded?: boolean
  }) => void) => () => void
  getSettings: () => Promise<AppSettings>
  saveSettings: (settings: Partial<AppSettings>) => Promise<void>
  getHistory: () => Promise<HistoryItem[]>
  addToHistory: (item: HistoryItem) => Promise<void>
  clearHistory: () => Promise<void>
  removeFromHistory: (id: string) => Promise<void>
  checkDuplicate: (url: string) => Promise<{ isDuplicate: boolean; title?: string; videoId?: string }>
  onHistoryAdded: (callback: (item: HistoryItem) => void) => () => void
  onBatchComplete: (callback: (info: { batchGroupId: string }) => void) => () => void
  openFile: (filePath: string) => Promise<void>
  openFolder: (filePath: string) => Promise<void>
  selectFolder: () => Promise<string | null>

  // Queue operations
  getQueue: () => Promise<QueueStatus>
  addToQueue: (item: {
    url: string
    title: string
    thumbnail?: string
    channel?: string
    format: string
    qualityLabel?: string
    audioOnly: boolean
    source: 'app' | 'extension'
    sourceType?: 'single' | 'playlist' | 'channel'
    contentType?: 'video' | 'audio' | 'subtitle' | 'video+sub'
    subtitleOptions?: SubtitleOptions
    subtitleDisplayNames?: string
    batchGroupId?: string
  }) => Promise<{ id: string; position: number }>
  removeFromQueue: (id: string) => Promise<void>
  cancelQueueItem: (id: string) => Promise<void>
  pauseQueueItem: (id: string) => Promise<boolean>
  resumeQueueItem: (id: string) => Promise<boolean>
  pauseQueue: () => Promise<void>
  resumeQueue: () => Promise<void>
  clearQueue: () => Promise<void>
  retryQueueItem: (id: string) => Promise<boolean>
  retryAllFailed: () => Promise<number>
  cancelRetry: (id: string) => Promise<boolean>
  setQueueItemPriority: (id: string, priority: number) => Promise<boolean>
  getQueueItemPriority: (id: string) => Promise<number | undefined>
  onQueueUpdate: (callback: (status: QueueStatus) => void) => () => void

  // Logger operations
  getErrorLogs: () => Promise<LogEntry[]>
  openLogFile: () => Promise<void>

  // Binary management
  checkBinary: () => Promise<boolean>
  downloadBinary: () => Promise<boolean>
  getBinaryStatus: () => Promise<{
    ytdlp: { installed: boolean; version: string | null; path: string | null }
    ffmpeg: { available: boolean; version: string | null; path: string | null }
    ffprobe: { available: boolean; path: string | null }
  }>
  onBinaryDownloadStart: (callback: (data: { name: string }) => void) => () => void
  onBinaryDownloadProgress: (callback: (data: { percent: number; downloaded: number; total: number }) => void) => () => void
  onBinaryDownloadComplete: (callback: (data: { path: string }) => void) => () => void
  onBinaryDownloadError: (callback: (data: { error: string }) => void) => () => void

  // FFmpeg management
  checkFfmpeg: () => Promise<boolean>
  downloadFfmpeg: () => Promise<boolean>
  getFfmpegPath: () => Promise<string>

  // Update operations
  checkForUpdates: () => Promise<UpdateInfo | null>
  downloadUpdate: () => Promise<string | null>
  installUpdate: () => Promise<void>
  getUpdateStatus: () => Promise<UpdateStatus>
  cancelUpdate: () => Promise<void>
  getChangelog: (body: string, version: string) => Promise<ChangelogData>
  markChangelogSeen: () => Promise<void>
  getUpdateState: () => Promise<UpdateState>
  skipUpdateVersion: (version: string) => Promise<void>
  resetUpdate: () => Promise<void>
  fetchChangelogFromMain: () => Promise<ChangelogData[]>

  // Update event listeners
  onUpdateChecking: (callback: () => void) => () => void
  onUpdateAvailable: (callback: (info: UpdateInfo) => void) => () => void
  onUpdateNotAvailable: (callback: () => void) => () => void
  onUpdateProgress: (callback: (progress: UpdateProgress) => void) => () => void
  onUpdateDownloaded: (callback: (filePath: string) => void) => () => void
  onUpdateError: (callback: (error: string) => void) => () => void
  onUpdateCancelled: (callback: () => void) => () => void
  onShowChangelog: (callback: (version: string) => void) => () => void
  onLinuxDeb: (callback: (filePath: string) => void) => () => void
  onLinuxAppImage: (callback: (filePath: string) => void) => () => void

  // PO Token operations
  getPotTokenStatus: () => Promise<PotTokenStatus>
  restartPotTokenServer: () => Promise<void>
  onPotTokenStatus: (callback: (status: PotTokenStatus) => void) => () => void

  // Search operations
  searchYouTube: (query: string, maxResults?: number) => Promise<SearchResult[]>

  // Queue Export/Import
  exportQueue: () => Promise<{
    canceled?: boolean
    success?: boolean
    path?: string
    itemCount?: number
  }>
  importQueue: () => Promise<{
    canceled?: boolean
    success?: boolean
    importedCount?: number
    failedCount?: number
    failedItems?: Array<{ title: string; error: string }>
    mode?: 'merge' | 'replace'
  }>

  // Tray operations
  isTraySupported: () => Promise<boolean>
  clearTaskbarBadge: () => Promise<void>

  // Analytics operations
  getAnalytics: () => Promise<AnalyticsData>
  getAnalyticsRange: (range: 'all' | 'today' | 'week' | 'month') => Promise<{
    current: AnalyticsData
    previous: AnalyticsData
  }>
  resetAnalytics: () => Promise<void>

  // Export operations
  exportHistory: (format: 'csv' | 'json' | 'markdown') => Promise<{
    canceled?: boolean
    success?: boolean
    path?: string
    count?: number
  }>

  // System operations
  shutdownSystem: () => Promise<void>

  // Cloud Sync
  verifyCloudSyncKey: (apiUrl: string, apiKey: string) => Promise<{
    success: boolean;
    data?: {
      success?: boolean;
      user?: { id: string; email: string; name: string | null; username: string | null };
      error?: string;
    };
    error?: string;
  }>
  getCloudSyncStatus: () => Promise<{ enabled: boolean; config: CloudSyncConfig | null }>
  startCloudSync: (config: { apiUrl: string; apiKey: string; userId: string; pollInterval?: number }) => Promise<boolean>
  stopCloudSync: () => Promise<boolean>
  onCloudSyncStatus: (callback: (status: CloudSyncStatus) => void) => () => void
}

export interface DailyStats {
  date: string
  downloads: number
  bytes: number
  successCount: number
  failCount: number
  bandwidthBytes: number
}

export interface AnalyticsData {
  totalDownloads: number
  totalBytes: number
  totalBandwidth: number
  timeSavedSeconds: number
  successCount: number
  failCount: number
  avgSpeed: number
  totalDownloadDuration: number
  formatBreakdown: Record<string, number>
  topChannels: Array<{ name: string; count: number }>
  dailyStats: DailyStats[]
  firstDownloadDate: string | null
  lastUpdated: string
}

declare global {
  interface Window {
    electronAPI: ElectronAPI
  }
}
